# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-24.21

packages:
- .

flags:
  cryptonite:
    support_rdrand: false

ghc-options:
  streaming-commons: -optc-Wno-pointer-sign -optc-Wno-duplicate-decl-specifier
