name: Nix Flake Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run Nix Flake Check
        # devenv needs `--impure`
        run: nix flake check --impure
